"""展示逻辑层：**纯函数**，无 I/O、无 GUI、无第三方依赖。

这一层的存在理由是被 CI 逼出来的（见设计稿 §06.3 / 实施方案 §2.1）：
``pyproject.toml`` 的覆盖率 ``source`` 已包含 ``app``，门槛 80%，
而 CI 跑在**无显示环境**——Tkinter 窗口代码在 CI 里根本执行不到。
所以「能测的规则」全部推到这里，``app/client/`` 只留「读快照 → 调用本层 → 画」。
"""

from __future__ import annotations

from app.present.bubble import aggregate_components, personal_components
from app.present.colors import (
    CLOSED_COLOR,
    DIM_COLOR,
    ON_DARK_TEXT,
    ON_LIGHT_TEXT,
    STATE_COLORS,
    STATE_FILLS,
    color_for,
    color_for_count,
    color_for_key,
    color_for_key_count,
    fill_for,
    fill_for_key,
    is_dim,
    on_fill,
)
from app.present.console import (
    CONSOLE_SECTIONS,
    KIND_FACT,
    KIND_READONLY,
    KIND_TEXT,
    KIND_UNWIRED,
    KIND_WIRED,
    KINDS,
    ConsoleItem,
    ConsoleSection,
    console_items,
    unwired_items,
    visible_sections,
)
from app.present.diag import diag_lines
from app.present.diff import changed_participants
from app.present.filters import (
    ATTENTION_ORDER,
    BUCKET_ALL,
    BUCKET_UNKNOWN,
    BUCKETS,
    SORT_ATTENTION,
    SORT_ID,
    SORTS,
    FilterOption,
    SortOption,
    bucket_of,
    filter_counts,
    filter_options,
    normalize_filter,
    normalize_sort,
    sort_options,
    sort_rows,
)
from app.present.grid import MAX_GRID_COLUMNS, columns_for, grid_cells, sort_key
from app.present.kpi import KpiCard, kpi_cards
from app.present.layout import (
    INSPECTOR_FULL,
    INSPECTOR_HIDDEN,
    INSPECTOR_NARROW,
    NAV_FULL,
    NAV_HIDDEN,
    NAV_ICONS,
    Layout,
    layout_for_width,
)
from app.present.roster import MASKED_TEXT, RosterRow, roster_rows
from app.present.scale import (
    SCALE_COMPACT,
    SCALE_ROOMY,
    SCALE_STANDARD,
    WIDTH_COMPACT,
    WIDTH_ROOMY,
    CardGeometry,
    card_geometry,
    columns_at,
    scale_for_width,
)
from app.present.shape import STATE_SHAPES, shape_for, shape_for_key
from app.present.skin import (
    BG,
    BRAND,
    BRAND_ACTIVE,
    BRAND_DISABLED,
    BRAND_HOVER,
    BRAND_SUBTLE,
    CARD_BG,
    HAIRLINE,
    HAIRLINE_STRONG,
    HEADER_BG,
    HIDDEN_BG,
    HIDDEN_FG,
    INK,
    INK_2,
    INK_3,
    INK_HI,
    MICRO,
    OK_TAG_BG,
    OK_TAG_FG,
    PANEL_BG,
    RADIUS_FULL,
    RADIUS_LG,
    RADIUS_MD,
    RADIUS_SM,
    RADIUS_XL,
    RADIUS_XS,
    RO_TAG_BG,
    RO_TAG_FG,
    SHADOW,
    SPACING_LG,
    SPACING_MD,
    SPACING_SM,
    SPACING_XL,
    SPACING_XS,
    UNWIRED_BG,
    UNWIRED_BORDER,
    UNWIRED_FG,
    UNWIRED_TAG_BG,
    UNWIRED_TAG_FG,
    WARN_TAG_BG,
    WARN_TAG_FG,
)
from app.present.status import FRESH_AGING_SECONDS, freshness, freshness_key, offline
from app.present.summary import (
    CLOSED_KEY,
    CLOSED_TEXT,
    DISPLAY_LABELS,
    LABEL_ORDER,
    LABEL_TEXT,
    RoomStats,
    Summary,
    room_stats,
    summarize,
)
from app.present.trend import DEFAULT_TREND_WINDOW, TrendBuffer, TrendSample
from app.present.visibility import HIDDEN_SCOPE_TEXT, visible_to

__all__ = [
    "ATTENTION_ORDER",
    "BG",
    "BRAND",
    "BRAND_ACTIVE",
    "BRAND_DISABLED",
    "BRAND_HOVER",
    "BRAND_SUBTLE",
    "BUCKET_ALL",
    "BUCKET_UNKNOWN",
    "BUCKETS",
    "CARD_BG",
    "CLOSED_COLOR",
    "CLOSED_KEY",
    "CLOSED_TEXT",
    "CONSOLE_SECTIONS",
    "DEFAULT_TREND_WINDOW",
    "DIM_COLOR",
    "DISPLAY_LABELS",
    "FRESH_AGING_SECONDS",
    "HAIRLINE",
    "HAIRLINE_STRONG",
    "HEADER_BG",
    "HIDDEN_BG",
    "HIDDEN_FG",
    "INK",
    "INK_2",
    "INK_3",
    "INK_HI",
    "INSPECTOR_FULL",
    "INSPECTOR_HIDDEN",
    "INSPECTOR_NARROW",
    "KINDS",
    "KIND_FACT",
    "KIND_READONLY",
    "KIND_TEXT",
    "KIND_UNWIRED",
    "KIND_WIRED",
    "LABEL_ORDER",
    "LABEL_TEXT",
    "HIDDEN_SCOPE_TEXT",
    "MASKED_TEXT",
    "MAX_GRID_COLUMNS",
    "MICRO",
    "NAV_FULL",
    "NAV_HIDDEN",
    "NAV_ICONS",
    "OK_TAG_BG",
    "OK_TAG_FG",
    "ON_DARK_TEXT",
    "ON_LIGHT_TEXT",
    "PANEL_BG",
    "RADIUS_FULL",
    "RADIUS_LG",
    "RADIUS_MD",
    "RADIUS_SM",
    "RADIUS_XL",
    "RADIUS_XS",
    "RO_TAG_BG",
    "RO_TAG_FG",
    "SCALE_COMPACT",
    "SCALE_ROOMY",
    "SCALE_STANDARD",
    "SHADOW",
    "SORTS",
    "SORT_ATTENTION",
    "SORT_ID",
    "SPACING_LG",
    "SPACING_MD",
    "SPACING_SM",
    "SPACING_XL",
    "SPACING_XS",
    "STATE_COLORS",
    "STATE_FILLS",
    "STATE_SHAPES",
    "UNWIRED_BG",
    "UNWIRED_BORDER",
    "UNWIRED_FG",
    "UNWIRED_TAG_BG",
    "UNWIRED_TAG_FG",
    "WARN_TAG_BG",
    "WARN_TAG_FG",
    "WIDTH_COMPACT",
    "WIDTH_ROOMY",
    "CardGeometry",
    "ConsoleItem",
    "ConsoleSection",
    "FilterOption",
    "KpiCard",
    "Layout",
    "RoomStats",
    "RosterRow",
    "SortOption",
    "Summary",
    "TrendBuffer",
    "TrendSample",
    "aggregate_components",
    "bucket_of",
    "card_geometry",
    "changed_participants",
    "color_for",
    "color_for_count",
    "color_for_key",
    "color_for_key_count",
    "columns_at",
    "columns_for",
    "console_items",
    "diag_lines",
    "fill_for",
    "fill_for_key",
    "filter_counts",
    "filter_options",
    "freshness",
    "freshness_key",
    "grid_cells",
    "is_dim",
    "kpi_cards",
    "layout_for_width",
    "normalize_filter",
    "normalize_sort",
    "offline",
    "on_fill",
    "personal_components",
    "room_stats",
    "roster_rows",
    "scale_for_width",
    "shape_for",
    "shape_for_key",
    "sort_key",
    "sort_options",
    "sort_rows",
    "summarize",
    "unwired_items",
    "visible_sections",
    "visible_to",
]
